[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/v1/chat/completions"
  to = "/.netlify/functions/chat"
  status = 200
  methods = ["POST"]
  
[[redirects]]
  from = "/v1/models"
  to = "/.netlify/functions/chat"
  status = 200
  methods = ["POST", "GET"]
