[build]
  functions = "netlify/functions"
  publish = "build"  # Directory of your static files, if applicable

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat-background"
  status = 200
  methods = ["POST"]
